In [1]:
import pandas as pd
import mlflow
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from mlflow.models import infer_signature

In [2]:
mlflow.set_tracking_uri("http://127.0.0.1:5000")

In [3]:
#Loading the dataset
X,y=datasets.load_iris(return_X_y=True)
X,y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [4]:
#spliting the data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [5]:
params={"penalty":"l2","solver":"lbfgs","max_iter":1000,"multi_class":"auto","random_state":42,}

In [6]:
clf=LogisticRegression(**params)

In [7]:
clf.fit(X_train,y_train)

/home/ronie-samuel/Documents/MLOps/MLFlow/venv/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=1000, multi_class='auto', random_state=42)

In [8]:
y_preds=clf.predict(X_test)
y_preds,y_test

(array([0, 2, 2, 1, 0, 0, 1, 1, 0, 1, 1, 2, 1, 2, 0, 1, 1, 0, 2, 1, 2, 0,
        2, 0, 2, 2, 2, 2, 0, 2]),
 array([0, 2, 2, 1, 0, 0, 1, 1, 0, 1, 1, 2, 1, 2, 0, 1, 1, 0, 2, 1, 2, 0,
        2, 0, 2, 2, 2, 2, 0, 2]))

In [9]:
accuracy=accuracy_score(y_preds,y_test)
accuracy

1.0

In [10]:
import mlflow.sklearn


mlflow.set_experiment("Initial-trained-model")
with mlflow.start_run():
    mlflow.log_params(params)
    mlflow.log_metric("Accuracy_Score",accuracy)
    mlflow.set_tag("Training Info","Basic LR Model")
    signature=infer_signature(X_train,clf.predict(X_train))
    mlflow.sklearn.log_model(
        sk_model=clf,artifact_path="iris_model",
        signature=signature,
        input_example=X_train,
        registered_model_name="Initial-trained-model")

    

2025/06/23 11:34:44 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
Registered model 'Initial-trained-model' already exists. Creating a new version of this model...
2025/06/23 11:34:46 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Initial-trained-model, version 3


🏃 View run respected-doe-631 at: http://127.0.0.1:5000/#/experiments/491174445896055916/runs/95c72b6ad81a4373b9d6be829227d05b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/491174445896055916


Created version '3' of model 'Initial-trained-model'.


In [11]:
params={"solver":"sag","penalty":"l2","max_iter":1000,"multi_class":"auto","random_state":1000}
clf=LogisticRegression(**params)

In [12]:
clf.fit(X_train,y_train)
y_preds=clf.predict(X_test)
accuracy=accuracy_score(y_preds,y_test)
accuracy

/home/ronie-samuel/Documents/MLOps/MLFlow/venv/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/ronie-samuel/Documents/MLOps/MLFlow/venv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


0.9666666666666667

In [15]:

mlflow.set_experiment("Initial-trained-model")
with mlflow.start_run():
    mlflow.log_params(params)
    mlflow.log_metric("Accuracy_Score",accuracy)
    mlflow.set_tag("Training Info","Basic LR Model")
    signature=infer_signature(X_train,clf.predict(X_train))
    model_info=mlflow.sklearn.log_model(
        sk_model=clf,artifact_path="iris_model",
        signature=signature,
        input_example=X_train,)    

2025/06/23 11:35:58 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.


🏃 View run zealous-robin-770 at: http://127.0.0.1:5000/#/experiments/491174445896055916/runs/9ee9c9447e5549f0a55db2ff5898e58a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/491174445896055916


In [16]:
loaded_model=mlflow.pyfunc.load_model(model_info.model_uri)
yLoadedModel_preds=loaded_model.predict(X_test)
columns=datasets.load_iris().feature_names
result=pd.DataFrame(X_test,columns=columns)
result["Actual Result"]=y_test
result["Predicted Redult"]=yLoadedModel_preds
result

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.0               3.6                1.4               0.2   
1                 7.2               3.0                5.8               1.6   
2                 7.7               3.8                6.7               2.2   
3                 5.5               2.3                4.0               1.3   
4                 4.9               3.6                1.4               0.1   
5                 5.5               3.5                1.3               0.2   
6                 5.6               3.0                4.1               1.3   
7                 6.7               3.1                4.7               1.5   
8                 5.8               4.0                1.2               0.2   
9                 6.9               3.1                4.9               1.5   
10                6.0               3.4                4.5               1.6   
11                6.7               3.3                5.7               2.5   
12                6.1               3.0                4.6               1.4   
13                5.8               2.8                5.1               2.4   
14                4.8               3.4                1.6               0.2   
15                6.1               2.8                4.7               1.2   
16                5.0               2.0                3.5               1.0   
17                5.3               3.7                1.5               0.2   
18                6.7               3.1                5.6               2.4   
19                5.2               2.7                3.9               1.4   
20                6.9               3.1                5.4               2.1   
21                5.0               3.4                1.6               0.4   
22                6.7               3.3                5.7               2.1   
23                5.4               3.4                1.5               0.4   
24                6.3               2.8                5.1               1.5   
25                6.2               3.4                5.4               2.3   
26                5.9               3.0                5.1               1.8   
27                6.4               3.2                5.3               2.3   
28                5.0               3.0                1.6               0.2   
29                6.4               3.1                5.5               1.8   

    Actual Result  Predicted Redult  
0               0                 0  
1               2                 2  
2               2                 2  
3               1                 1  
4               0                 0  
5               0                 0  
6               1                 1  
7               1                 1  
8               0                 0  
9               1                 1  
10              1                 1  
11              2                 2  
12              1                 1  
13              2                 2  
14              0                 0  
15              1                 1  
16              1                 1  
17              0                 0  
18              2                 2  
19              1                 1  
20              2                 2  
21              0                 0  
22              2                 2  
23              0                 0  
24              2                 1  
25              2                 2  
26              2                 2  
27              2                 2  
28              0                 0  
29              2                 2

In [ ]:
import mlflow.sklearn
import mlflow.sklearn
model_name="Initial-trained-model"
model_version="latest"
model_uri=f"models://{model_name}/{model_version}"

model=mlflow.sklearn.load_model(model_uri)
model

RestException: RESOURCE_DOES_NOT_EXIST: Model 'Version 3' not found